### ISSUE TITLE
源码 x86 环境编译报错

### ISSUE THREAD

**Issue by chenqi-wds** [hwCloudDBSDDS/dds#5]
src/mongo/db/fts/jieba/HMMModel.hpp: In member function 'bool cppjieba::HMMModel::LoadEmitProb(const string&, cppjieba::EmitProbMap&)':
src/mongo/db/fts/jieba/HMMModel.hpp:103:22: error: 'ERROR' was not declared in this scope
                 XLOG(ERROR) << "emitProb illegal.";
                      ^
src/mongo/db/fts/jieba/HMMModel.hpp:103:27: error: 'XLOG' was not declared in this scope
                 XLOG(ERROR) << "emitProb illegal.";
                           ^
src/mongo/db/fts/jieba/HMMModel.hpp:107:22: error: 'ERROR' was not declared in this scope
                 XLOG(ERROR) << "TransCode failed.";
                      ^
src/mongo/db/fts/jieba/HMMModel.hpp:107:27: error: 'XLOG' was not declared in this scope
                 XLOG(ERROR) << "TransCode failed.";

**Comment by wolfkdy** [comment]
@chenqi-wds , it seems this file lacks "limonp/Logging.hpp" headfile. Would you please add
```
#include "limonp/Logging.hpp" 
```
to HMMModel.hpp at file's include part and retry?

**Comment by chenqi-wds** [comment]
thx,  I have added it and now there is another error.
src/mongo/db/fts/jieba/HMMSegment.hpp: In member function 'void cppjieba::HMMSegment::Viterbi(limonp::LocalVector<cppjieba::RuneStr>::const_iterator, limonp::LocalVector<cppjieba::RuneStr>::const_iterator, std::vector<long unsigned int>&) const':
src/mongo/db/fts/jieba/HMMSegment.hpp:147:74: error: 'MIN_DOUBLE' was not declared in this scope
                 model_->GetEmitProb(model_->emitProbVec[y], begin->rune, MIN_DOUBLE);
                                                                          ^
src/mongo/db/fts/jieba/HMMSegment.hpp:156:31: error: 'MIN_DOUBLE' was not declared in this scope
                 weight[now] = MIN_DOUBLE;

**Comment by wolfkdy** [comment]
MIN_DOUBLE is defined in  DictTrie.hpp，these compiling errors may be caused of compiler's minor differences.
But they are easy to fix.
To this error, just include DictTrie.hpp to HMMSegment.hpp and it should work.

Please try to fix all these errors and make a merge request, thanks! @chenqi-wds

**Comment by chenqi-wds** [comment]
thx，it has been successful
