### ISSUE TITLE
the detail of query stage memory limit

### ISSUE THREAD

**Issue by rickif** [hwCloudDBSDDS/dds#8]
I wonder how the dds implements the memory limit, mainly about how to measure the memory that the query use.
Maybe there's a lack of detail commit history, which makes me unable to find the exact code. Is there any guidance to the code about the memory limiting?

**Comment by ytwork** [comment]
> I wonder how the dds implements the memory limit, mainly about how to measure the memory that the query use.
> Maybe there's a lack of detail commit history, which makes me unable to find the exact code. Is there any guidance to the code about the memory limiting?

Please reference this wiki: https://github.com/hwCloudDBSDDS/dds/wiki/QueryStage-Memory-Limit

**Comment by wolfkdy** [comment]
@rickif  https://github.com/hwCloudDBSDDS/dds/blob/c6b5a15fc19c4ea844cf3be8e9ab8b6b9b2e5d46/src/mongo/db/stats/counters.h#L132

**Comment by wolfkdy** [comment]
@rickif I will close this issue. you may open another one for more details.
